# Generated by Django 4.2.27 on 2026-02-01 13:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name or identifier for this reed', max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When the reed was created/started')),
                ('status', models.CharField(choices=[('new', 'New'), ('breaking_in', 'Breaking In'), ('prime', 'Prime'), ('declining', 'Declining'), ('retired', 'Retired')], default='new', max_length=20)),
                ('cane_source', models.CharField(blank=True, help_text='Source or brand of cane', max_length=200)),
                ('shape', models.CharField(blank=True, help_text='Shape used for this reed', max_length=100)),
                ('gouge_thickness', models.DecimalField(blank=True, decimal_places=2, help_text='Gouge thickness in mm', max_digits=4, null=True)),
                ('notes', models.TextField(blank=True, help_text='General notes about this reed')),
                ('total_play_time_minutes', models.IntegerField(default=0, help_text='Total time played with this reed in minutes')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='UsageSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(blank=True, help_text='Duration in minutes (calculated from start/end time)', null=True)),
                ('context', models.CharField(blank=True, help_text="e.g., 'Practice', 'Rehearsal', 'Performance', 'Lesson'", max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('reed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_sessions', to='reeds.reed')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='QualitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('tone_quality', models.IntegerField(blank=True, help_text='Tone quality rating (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('response', models.IntegerField(blank=True, help_text='Response/articulation rating (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('intonation', models.IntegerField(blank=True, help_text='Intonation quality rating (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('stability', models.IntegerField(blank=True, help_text='Stability/consistency rating (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('ease_of_playing', models.IntegerField(blank=True, help_text='Overall ease of playing (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('overall_rating', models.IntegerField(blank=True, help_text='Overall rating (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('notes', models.TextField(blank=True)),
                ('reed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_snapshots', to='reeds.reed')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('modification_type', models.CharField(choices=[('clip', 'Clip'), ('scrape_tip', 'Scrape Tip'), ('scrape_heart', 'Scrape Heart'), ('scrape_back', 'Scrape Back'), ('scrape_rails', 'Scrape Rails'), ('adjust_wire', 'Adjust Wire'), ('trim_corners', 'Trim Corners'), ('balance', 'Balance'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the modification')),
                ('goal', models.CharField(blank=True, help_text='What issue were you trying to fix or improve?', max_length=200)),
                ('success_rating', models.IntegerField(blank=True, help_text='How successful was this modification? (1-10)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('reed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifications', to='reeds.reed')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
